version: '3.8'

services:
  # Confluent Zookeeper service
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  # Confluent Kafka service
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9091
      - KAFKA_LISTENER_NAME_INTERNAL=INTERNAL
      - KAFKA_LISTENER_INTERNAL_PORT=9093
      - KAFKA_LISTENER_INTERNAL=INTERNAL
      - KAFKA_LISTENER_PORT=9092

      # Zookeeper connection
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      
      # Set replication factors for internal topics to 1 (for single broker setup)
      - KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
      
      - KAFKA_LISTENER_HOSTNAME=0.0.0.0

      # Kafka auto create topics and default topic
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_DEFAULT_TOPIC=travel-log
    ports:
      - "9092:9092"
      - "9091:9091"
    depends_on:
      - zookeeper
    networks:
      - kafka_network


  # Kafka UI service
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - "8080:8080"
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge
